image:
  repository: localhost/rainman
  tag: dev
  pullPolicy: IfNotPresent

secret:
  openRouterApiKey: ${KIND_OPEN_ROUTER_API_KEY}

resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    cpu: 250m
    memory: 192Mi
