apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kb-agent.fullname" . }}
  labels:
    {{- include "kb-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENROUTER_API_KEY: {{ .Values.secret.openRouterApiKey | quote }}
